### ISSUE TITLE
Options window without displaying settings

### ISSUE THREAD

**Issue by UnlimitedChild** [ThunderCls/x64dbg_acid_lime_theme#1]
Hi,

the latest debugger version does not display options, they all look identical, options cannot be switched. 

![Image 1](https://user-images.githubusercontent.com/16466330/60668543-85cd6d80-9e6c-11e9-944a-db9d50dafa51.png)

I did not check other styles, but probably there is the same problem. 

Regards

**Comment by ThunderCls** [comment]
Check that you have the "icons" folder inside your x64dbg version for each platform (x32/x64). In case you're using the x64dbg-updater plugin make sure you modify your _update.bat by adding:

inside the :removefile block
if %1 == "release\x32\style.css" goto :eof
if %1 == "release\x64\style.css" goto :eof

and inside the :removedir block

if %1 == "release\x32\icons" goto :eof
if %1 == "release\x64\icons" goto :eof

To prevent the plugin from deleting your theme files every time you update x64dbg.

![image](https://user-images.githubusercontent.com/13303069/60680495-890b2e00-9e59-11e9-92a2-8ea96795c768.png)

**Comment by UnlimitedChild** [comment]
Thanks, I found out that the plugin https://github.com/horsicq/nfdx64dbg breaks these settings. I repeated the experiment several times. Below I have put an example for testing...
[x64.zip](https://github.com/ThunderCls/x64dbg_acid_lime_theme/files/3360271/x64.zip)

**Comment by ThunderCls** [comment]
You are correct that plugin is preventing the images for the theme to be loaded, you should maybe post this issue in the plugin author's repo.
